// DO NOT EDIT THIS FILE
// This file is generated automatically by the typed-scss-modules library
export type Styles = {
  card: string
  center: string
  code: string
  content: string
  description: string
  grid: string
  logo: string
  main: string
  rotate: string
  vercelLogo: string
}

export type ClassNames = keyof Styles

declare const styles: Styles

export default styles
