name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        name: Setup

      - name: Lint
        run: pnpm lint

  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        name: Setup

      - name: Prettier
        run: pnpm format:check

  stylelint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        name: Setup

      - name: Stylelint
        run: pnpm stylelint

  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        name: Setup

      - name: Type check
        run: pnpm type-check

  build:
    runs-on: ubuntu-latest
    needs: [eslint, prettier, stylelint, type-check]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        name: Setup

      - name: Build
        run: pnpm build --no-lint
